### ISSUE TITLE
Feature request: Add label / named passes

### ISSUE THREAD

**Issue by daunce** [run-pass/run-pass#2]
Run pass has made park runs more enjoyable! Thank you for this! 

My kids now join in, and instead of them having iPhones/ watches, I’d like to add their pass to my watch, but the pass lists their Axxxxx ID which I won’t remember. 

Would it be possible to add a label, or customise the existing one to use either Axxxxx or a custom entry? I’d like to name each pass so I can choose the right one to scan. 

Thanks again for some an amazing utility!

**Comment by billytrend** [comment]
Hey @daunce, thanks for your message and the idea. This should be working now. Let me know if you encounter any issues

**Comment by daunce** [comment]
Thank you very much @billytrend! I used it at this morning’s Parkrun! Great work!
